services:
  mongo:
    image: mongo:7
    container_name: queueflow-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: queueflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: queueflow-backend
    restart: unless-stopped
    env_file: ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000/api
    container_name: queueflow-frontend
    restart: unless-stopped
    env_file: ./frontend/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
  redis_data:
